#[[headers]]
#  # Define which paths this specific [[headers]] block will cover.
#  for = "/*"
#    [headers.values]
#    Access-Control-Allow-Origin = "https://planter.garden"
#    Access-Control-Allow-Methods = "GET"
